### ISSUE TITLE
Add `defaults` option to `org-pandoc-valid-options`

### ISSUE THREAD

**Issue by bsag** [emacsorphanage/ox-pandoc#11]
I use pandoc's `--defaults` option a lot now to simplify keeping standardised settings for different input/output formats so that I just have to specify one command line option to set a lot of options consistently.

Could `defaults` be added to `org-pandoc-valid-options`? That way it would be easy to configure ox-pandoc to be consistent with command line usage by adding configuration such as:

```emacs-lisp
(setq org-pandoc-options-for-latex-pdf '((defaults . org2articlepdf))
```

where org2articlepdf is a YAML file ~/.pandoc/defaults/org2articlepdf.yaml.

Thanks for continuing to maintain ox-pandoc - I'm excited at the prospect of being able to use org-cite with pandoc eventually!

**Comment by a-fent** [comment]
Thanks for the pointer to this useful option in pandoc. 

Fixed by https://github.com/emacsorphanage/ox-pandoc/commit/b2e43b936249de2a100afb4262698105c39ce289
