### ISSUE TITLE
Problem installing ox-pandoc 

### ISSUE THREAD

**Issue by Enrico68** [emacsorphanage/ox-pandoc#12]
Lately got some problems with pandoc exporter. I have installed Emacs on a new machine (OSX 10.15.7), I have downloaded the `ox-pandoc.el` file and put on my `lisp` directory. After `require 'ox-pandoc` got this error :

> org-export-register-backend: Cannot use unknown "org" back-end as a parent

**Comment by a-fent** [comment]
Hmm. I'd recommend using a package manager if you can. E.g. `install-package` or `(use-package ox-pandoc :ensure t)`

Is org-mode loaded already by the time you try to require `ox-pandoc`?

**Comment by Enrico68** [comment]
I have removed the package and reinstalled with 

```
(use-package ox-pandoc
  :defer 1
  :ensure t)
(require 'ox-pandoc)
```
 And got 

```
Loading async...done
org-export-register-backend: Cannot use unknown "org" back-end as a parent
Error running timer ‘require’: (error "Cannot use unknown \"org\" back-end as a parent")
```

Very strange. I was using for years without problems...

**Comment by a-fent** [comment]
Did you manage to resolve this? The only thing I can see is that you maybe need to ensure that ox-pandoc is loaded after org, for example with `:after (org)` in your `use-package` declaration.

**Comment by a-fent** [comment]
Assuming resolved, please re-open if necessary.
