### ISSUE TITLE
Support org-export-snippet-backend

### ISSUE THREAD

**Issue by gvol** [emacsorphanage/ox-pandoc#15]
I ran into an issue in which I wanted to export a macro differently in LaTeX (`ox-latex`) then in rtf (`ox-pandoc`).  I can easily create an "export snippet" that only exports in LaTeX, but such a thing doesn't work for `ox-pandoc`.  

```
#+MACRO: written @@latex:\marginpar{This was written on $1}@@
```

It would be great if it could support this, ideally with both `@@rtf:MY STUFF HERE@@` and `@@pandoc:MY STUFF HERE@@`, but either one would probably be sufficient for my needs at this time.

I'm not sure how active this repo is maintained, but I might be able to find some time to make a PR if that would be better.

**Comment by a-fent** [comment]
Thanks for the report, that sounds like something that we should support. Could you:

1) Post a link to the section of the Org Manual that describes the feature (it's not one I've used)
2) Check that the feature works correctly if you use pandoc directly on the file (rather than via ox-pandoc)

If it's a type of element then it could be quite simple, along the lines of `org-pandoc-export-block` which passes through the element verbatim to pandoc. PR of course welcome.

**Comment by gvol** [comment]
I can't find where it talks about it as a general feature but, for example, if you read in `(info "(org)Quoting LaTeX code")` it talks about using `@@latex:XXX@@ to export some stuff only in LaTeX export.  Same with `(info "(org)Advanced topics in ODT export")` and several other places.

http://git.savannah.gnu.org/cgit/emacs/org-mode.git/tree/lisp/org-element.el#n3189 is where it's parsed and assigned a backend.  http://git.savannah.gnu.org/cgit/emacs/org-mode.git/tree/lisp/ox.el#n867 allows backend translation.  And http://git.savannah.gnu.org/cgit/emacs/org-mode.git/tree/lisp/ox-texinfo.el#n48 seems to be where it's hooked up.  

I've been playing around a bit and I have a cargo-culted partial solution: `@@pandoc:XXX@@` works but I don't know enough about `pandoc` to know if it's even possible to have `@@rtf:XXX@@` work.  

I created https://github.com/emacsorphanage/ox-pandoc/pull/16.  Let me know what work you think it needs.

**Comment by a-fent** [comment]
Should be fixed by: https://github.com/emacsorphanage/ox-pandoc/commit/0a35d0fbfa56bdd9ec5ba5bac2fe002b61c05c52
