### ISSUE TITLE
FR: add ability to disable built-in numbering

### ISSUE THREAD

**Issue by PRESFIL** [emacsorphanage/ox-pandoc#21]
Built-in numbering is a nice default, but we need the ability to turn it off if
needed. It numbering conflicts with external `pandoc`'s numbering filters,
such as `pandoc-crossref` or `pandoc-xnos`. It would be nice if an additional
keyword would be implemented that would control all preprocessing (numbering,
particulary):

```org
#+PANDOC_PREPROCESSING: num:nil
```

instead of completely removing the functionality. This would improve the
reproducibility of the documents, instead of completely removing the
functionality.

The example provides the ability to specify a list of options `variable:value`
for the ability to disable/enable several options at once.  I don't know, does `ox-pandoc`
performs anything other than numbering?

**Comment by a-fent** [comment]
Thank you again for the report. As of https://github.com/emacsorphanage/ox-pandoc/commit/8a0882ba772e85cb97d46491f23434e996914c64 ox-pandoc no longer does any (re-)numbering of figures, tables etc. Numbering via pandoc filters like pandoc-crossref and pandoc-xnos should be respected.
