### ISSUE TITLE
Problem when loading the back-end pandoc

### ISSUE THREAD

**Issue by ronisbr** [emacsorphanage/ox-pandoc#24]
Hi!

After installing the newest version (`master`), I am getting the following error when trying to export to HTML5:

```
Problems while trying to load export back-end ‘pandoc’
load-with-code-conversion: Invalid read syntax: ")", 1583, 15
```

**Comment by a-fent** [comment]
Assuming this is fixed by the current release. Please do get back with any feedback or test cases on equations.

**Comment by ronisbr** [comment]
Thanks!
