### ISSUE TITLE
Bump Version inside ox-pandoc.el

### ISSUE THREAD

**Issue by mekeor** [emacsorphanage/ox-pandoc#27]
Hello. [The `ox-pandoc.el` source file still has `Version: 1.210925` listed](https://github.com/emacsorphanage/ox-pandoc/blob/66c32cca4f6047dd7e0f77f10bd565a2d83d4729/ox-pandoc.el#L12). If I understand correctly, the current version of ox-pandoc is `2.0`, as can be seen by the Git tags. It'd be nice if the inline version statement would reflect that too.

**Comment by a-fent** [comment]
Thanks for the heads up. Corrected.
