### ISSUE TITLE
Org multicolumn syntax is not supported

### ISSUE THREAD

**Issue by lf-araujo** [emacsorphanage/ox-pandoc#34]
I was wondering if it would be possible to have a multiple column beamer slide using [ox-pandoc](https://github.com/kawabata/ox-pandoc) in emacs orgmode. Below is the typical syntax for multiple columns, this however does not work if pandoc-export-to-beamer is used.

```
#+TITLE: Title 
#+SUBTITLE: Meetings presentation
#+AUTHOR: Me [fn:NAME: a definition]
#+PANDOC_OPTIONS: number-sections:nil
#+PANDOC_VARIABLES: classoption:"aspectratio=169"
#+PANDOC_VARIABLES: suppress-bibliography:true
#+PANDOC_VARIABLES: lang:en
#+PANDOC_VARIABLES: mainfont:Roboto

* Title

- Hi!

* Two columns

** A block                                           :BMCOL:
    :PROPERTIES:
    :BEAMER_env: ignoreheading
    :BEAMER_col: 0.4
    :END:
    - this slide consists of two columns
    - the first (left) column has no heading and consists of text
    - the second (right) column has an image and is enclosed in an
      @example@ block

** A screenshot :BMCOL:
    :PROPERTIES:
    :BEAMER_col: 0.6
    :BEAMER_env: example
    :END:

```

[![enter image description here][1]][1]

This does not work, any other syntax that I am unaware that I can use to try getting multiple columns in a slide?

  [1]: https://i.stack.imgur.com/dbOy1.png

**Comment by yantar92** [comment]
Alex Fenton ***@***.***> writes:

> Thanks for the question. Pandoc has support for multi-column layouts in HTML and Beamer presentations. It's probably easiest just to use this rather than the tag/property syntax of Org's Beamer exporter.
>
> ``` {.org}
> * Two columns
> :PROPERTIES:
> :class:    columns
> :END:
> ...
> Note that you may need to add `#+options: prop:t` to the document header to ensure that property drawers are passed through to Pandoc.

If just replacing properties with other properties is enough, ox-pandoc
may as well automate it.

P.S. Where is this pandoc's behavior documented?

-- 
Ihor Radchenko // yantar92,
Org mode contributor,
Learn more about Org mode at <https://orgmode.org/>.
Support Org development at <https://liberapay.com/org-mode>,
or support my work at <https://liberapay.com/yantar92>

**Comment by a-fent** [comment]
On 17/01/2024 13:59, Ihor Radchenko wrote:

> If just replacing properties with other properties is enough, ox-pandoc
> may as well automate it.

Maybe. I don't think pandoc replicates one-to-one the options that `ox-beamer.el` offers (e.g. `BEAMER_ENV`).

I'd prefer to add code only where it fixes generic Org syntax / behaviour, not the details of individual bundled Org-mode exporters. ox-pandoc is an alternative to/replacement for ox-beamer, not an implementation of it.

The default value for `org-export-with-properties` for ox-pandoc should probably be true, though, if it doesn't have any side-effects.

> P.S. Where is this pandoc's behavior documented?

Nowhere very clearly 🙂 I wasted a few hours messing around with Lua filters before I just tried it, based on:

https://pandoc.org/chunkedhtml-demo/10.1-structuring-the-slide-show.html
https://pandoc.org/chunkedhtml-demo/10.6-columns.html

plus the Pandoc source and various stackexchange/github things

**Comment by yantar92** [comment]
Alex Fenton ***@***.***> writes:

>> If just replacing properties with other properties is enough, ox-pandoc
>> may as well automate it.
>
> Maybe. I don't think pandoc replicates one-to-one the options that `ox-beamer.el` offers (e.g. `BEAMER_ENV`).
>
> I'd prefer to add code only where it fixes generic Org syntax / behaviour, not the details of individual bundled Org-mode exporters. ox-pandoc is an alternative to/replacement for ox-beamer, not an implementation of it.

Fair enough. Then, it would make sense to explain these peculiarities of
beamer export in the readme/documentation. Or at least point to relevant
pandoc resources.

> The default value for `org-export-with-properties` for ox-pandoc should probably be true, though, if it doesn't have any side-effects.

None that I am aware of. At least, not on the Org mode side of things.
As long as pandoc can treat Org mode property drawers correctly and make
use of them, it should be fine to export with properties.
If you want to play completely safe, you may set
`org-export-with-properties' to a list of property names that are known
to be useful and safe.

>> P.S. Where is this pandoc's behavior documented?
>
> Nowhere very clearly 🙂 I wasted a few hours messing around with Lua filters before I just tried it, based on:
>
> https://pandoc.org/chunkedhtml-demo/10.1-structuring-the-slide-show.html
> https://pandoc.org/chunkedhtml-demo/10.6-columns.html

I saw both, and the second one is completely confusing...

-- 
Ihor Radchenko // yantar92,
Org mode contributor,
Learn more about Org mode at <https://orgmode.org/>.
Support Org development at <https://liberapay.com/org-mode>,
or support my work at <https://liberapay.com/yantar92>

**Comment by lf-araujo** [comment]
Thank you very much both of you, the properties above fixes the issue.

**Comment by lf-araujo** [comment]
Not sure if I should open a new issue, but how do I resize a figure?


I tried :

#+out.width: 10
[file:figure.png]

and 

#+header: :width 10 :height 10
[file:figure.png]
