### ISSUE TITLE
Is it possible to align center  a picture for the beamer output?

### ISSUE THREAD

**Issue by lf-araujo** [emacsorphanage/ox-pandoc#36]
#+ATTR_HTML :align center 

Does not seem to work.

**Comment by yantar92** [comment]
lf_araujo ***@***.***> writes:

> #+ATTR_HTML :align center 

Try #+ATTR_BEAMER: :align center

-- 
Ihor Radchenko // yantar92,
Org mode contributor,
Learn more about Org mode at <https://orgmode.org/>.
Support Org development at <https://liberapay.com/org-mode>,
or support my work at <https://liberapay.com/yantar92>
