### ISSUE TITLE
Exportation of code+results of org src blocks fails

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [emacsorphanage/ox-pandoc#37]
Reminescent of [Issue 30 in the formek Kawabata's tree](https://github.com/kawabata/ox-pandoc/issues/30) : using construct such as : 

```
#+begin_src emacs-lisp ;exports both :results values  (+ 2 2)
#+end_src
```

exports correctly to PDF via LaTeX and to ODT using Org's native exporters (`C-c C-e l p` and `C c C-e o o`), but fails to export correctly to PDF, ODT or DOCX with `ox-pandoc` (`C-c C-e p L`, `C-c C-e p O`, `C-c C-e p X`) : the code *is* exported, but the results are not.

Here is a minimal (non-)working example (source + exports) : 

[MNWE.zip](https://github.com/emacsorphanage/ox-pandoc/files/14937943/MNWE.zip)

This deprives us of some interesting export applications...

**Comment by yantar92** [comment]
This has nothing to do with ox-pandoc itself. Just an edge case with ox-org export.
Fixed on Org mode side, on main (development branch).
https://git.savannah.gnu.org/cgit/emacs/org-mode.git/commit/?id=c6c5474b7e96fa0c7d858d166ae698e6b5ca69ae
