### ISSUE TITLE
bug: ox-pandoc, #+latex and tables

### ISSUE THREAD

**Issue by pank** [emacsorphanage/ox-pandoc#4]
Hi,

If there's a `#+latex` keyword between two tables ox-pandoc see them as one. Example:

```org
| a | b |

#+latex: 
| c | d |
```

this is exported to docx as:
```org
| a | b |
| c | d |
```

Thanks,
Rasmus

**Comment by a-fent** [comment]
Hi - could you point me to the bit of the Org Manual which explains what the expected behaviour is here? 

Is the meaning: following table should be converted to LaTeX and only included  if exporting to LaTeX target?

**Comment by pank** [comment]
Oh, that is an artificial example. `#+latex: code` just insert `code` in when exporting to LaTeX (and probably modes that are derived from `ox-latex.el` like `ox-beamer.el` ([manual](https://orgmode.org/org.html#Quoting-LaTeX-code)). 

So a more realistic example would be following where line spacing is increased for the second table. 

```org
| a | b |

#+latex: \renewcommand{\arraystretch}{1.1} 
| c | d |
```

**Comment by a-fent** [comment]
Thanks. Seems to be working as expected for me. Using `org-pandoc-export-as-latex` I get: 
```
\begin{longtable}[]{@{}ll@{}}
\toprule
\endhead
a & b \\
\bottomrule
\end{longtable}

\renewcommand{\arraystretch}{1.1}

\begin{longtable}[]{@{}ll@{}}
\toprule
\endhead
c & d \\
\bottomrule
\end{longtable}
```

And with Org mode's default exporter (`C-c C-e l L`) I get:
```
\begin{center}
\begin{tabular}{ll}
a & b\\
\end{tabular}
\end{center}

\renewcommand{\arraystretch}{1.1}
\begin{center}
\begin{tabular}{ll}
c & d\\
\end{tabular}
\end{center}
```
Exactly how the tables are exported to LaTeX is different, but that's as I'd expect, the inserted code is there in both cases.

You mention docx but code in `#+LATEX:` shouldn't appear when exporting to docx, right?

**Comment by pank** [comment]
Hi,

I am using pandoc for docx (because other people like the commenting 
functions...) And ox-latex for the actual document.

So latex works fine. And the #+latex shouldn't matter. But it seems to 
do, at least for docx. Pandoc HTML4 export seemed to work ok, though.

I will check if it's vanilla pandoc issue.

Thanks,
Rasmus

**Comment by a-fent** [comment]
OK, I understand the problem now (I use pandoc for a similar reason, incidentally). 

It seems to be an issue with pandoc itself: used directly, it issues a single table in docx even if separated by a `#+LATEX` keyword. 

I found that normal whitespace is eaten, but if I put a non-breaking space, it forces the tables apart. Maybe a workaround?

**Comment by pank** [comment]
As a workaround I am using @@latex:$CMD@@. Or actually an org macro that 
expands to a latex snippet.

But OK thanks for confirming that it is a pandoc bug.

I am not entirely sure yet where ox-pandoc ends and pandoc starts as I 
have never used pandoc before. (But it's so much better than ox-odt now 
for wordy formats that it cannot be ignored). I will try to be more 
careful distinguish between pandoc and ox-pandoc in the future.

**Comment by pank** [comment]
https://github.com/jgm/pandoc/issues/7724
